#version 450
#extension GL_EXT_shader_explicit_arithmetic_types_int8 : require
#extension GL_EXT_shader_explicit_arithmetic_types_int64 : require
#extension GL_EXT_shader_explicit_arithmetic_types_float16 : require
#extension GL_EXT_shader_16bit_storage : require
struct block_tq4_0 { uint8_t qs[64]; int8_t qjl[16]; float16_t d; float16_t padding; };
layout (push_constant) uniform parameter {
    uint ne; uint ne00; uint ne01; uint ne02; uint ne03; uint nb00; uint nb01; uint nb02; uint nb03;
    uint ne10; uint ne11; uint ne12; uint ne13; uint nb10; uint nb11; uint nb12; uint nb13;
    uint ne20; uint ne21; uint ne22; uint ne23; uint nb20; uint nb21; uint nb22; uint nb23;
    uint misalign_offsets;
} p;
uint get_aoffset() { return p.misalign_offsets >> 16; }
uint get_doffset() { return p.misalign_offsets & 0xFFFF; }
layout (binding = 0) readonly buffer A {block_tq4_0 data_a[];}; layout (binding = 1) writeonly buffer D {float16_t data_d[];}; layout(local_size_x = 64, local_size_y = 1, local_size_z = 1) in; void main() { uint block_idx = gl_WorkGroupID.x; if (block_idx >= (p.ne + 127) / 128) return; uint tid = gl_LocalInvocationID.x; float d = float(data_a[get_aoffset() + block_idx].d); uint vui = uint(data_a[get_aoffset() + block_idx].qs[tid]); data_d[get_doffset() + block_idx * 128 + tid * 2 + 0] = float16_t(float(int(data_a[get_aoffset() + block_idx].qjl[vui & 0x0F])) * d); data_d[get_doffset() + block_idx * 128 + tid * 2 + 1] = float16_t(float(int(data_a[get_aoffset() + block_idx].qjl[vui >> 4])) * d); }